name: Build and Deploy Microservices

on:
  push:
    branches:
      - main  # 仅当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: 构建并推送 document-service 镜像
      - name: Build and Push Document Service
        run: |
          cd document-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/document-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/document-service:latest

      # Step 4: 构建并推送 gateway-service 镜像
      - name: Build and Push Gateway Service
        run: |
          cd gateway-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest

      # Step 5: 构建并推送 user-service 镜像
      - name: Build and Push User Service
        run: |
          cd user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      # Step 6: 配置 kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 7: 配置 Kubernetes 集群上下文
      - name: Set up K8s context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.KUBE_CONFIG }}

      # Step 8: 部署到 Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/document-service-deployment.yaml
          kubectl apply -f k8s/document-service-service.yaml
          kubectl apply -f k8s/gateway-service-deployment.yaml
          kubectl apply -f k8s/gateway-service-service.yaml
          kubectl apply -f k8s/user-service-deployment.yaml
          kubectl apply -f k8s/user-service-service.yaml
